import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getDecl } from "../u/stringer";
import BasicButton from "../c/BasicButton";
import { useCallback, useState } from "react";

const Home: NextPage = () => {
  const [decl, setDecl] = useState(getDecl());

  const newDecl = useCallback(() => {
    setDecl(getDecl());
  }, [setDecl]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{decl}</h1>

        <p className={styles.description}>
          <BasicButton onClick={newDecl} label="re-declare" />
        </p>
      </main>

      <footer className={styles.footer}>penned by poeticnetworks</footer>
    </div>
  );
};

export default Home;
